title: Barbara Stork # your name (or website title) here
logo: "/images/portfolioBlue2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Innovative technical writer</b> with 10+ years of technical documentation expertise, designing and authoring technical content for diverse audiences (<b>end-users</b>, <b>administrators</b>, and <b>developers</b>). Proven ability to <b>lead others</b>, <b>manage projects</b>,  and <b>work cross-functionally</b> with teams across the organization. <b>Leveraging developer experience</b> to bridge communication with subject matter experts. Enthusiastic learner and <b>problem solver</b>, committed to developing expert-level expertise in products, tools, and processes. 
  <br><br>
  <a target="_blank" href="https://www.linkedin.com/in/barbara-stork">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
